# Defaults for sample CycleCloud storage module

# Scratch
STORAGE_SCRATCH_MODE="auto"       # auto|none
SCRATCH_MOUNTPOINT="/mnt/scratch"
FS_TYPE="ext4"                   # ext4|xfs
SCRATCH_REQUIRED="false"          # true|false

# Ephemeral RAID-0 aggregation
AZURE_EPHEMERAL_AGGREGATION="auto"   # auto|mdadm|none
AZURE_EPHEMERAL_MIN_DISKS="2"
AZURE_EPHEMERAL_MD_DEVICE="/dev/md0"
AZURE_EPHEMERAL_MD_CHUNK="512K"
AZURE_EPHEMERAL_FORCE_REFORMAT="0"

# Shared
STORAGE_SHARED_MODE="none"        # none|nfs|anf
SHARED_MOUNTPOINT="/shared"
NFS_SERVER=""
NFS_EXPORT=""
NFS_MOUNT_OPTS="defaults,_netdev,nofail"

# Debug
STORAGE_DEBUG="false"
